/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
//import org.example.Library;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Library classUnderTest = new Library();
        boolean result = classUnderTest.someLibraryMethod();
        System.out.println(result);
        int res = classUnderTest.add(1,2);
        System.out.println(res);
    }
}
